- CHANGELOG.md
- src/Extractor/FromSourceMappingExtractor.php
- src/Extractor/FromTargetMappingExtractor.php
- src/Extractor/SourceTargetMappingExtractor.php
- src/MapperMetadata.php
- tests/AutoMapperTest.php
`mapPrivatePropertiesAndMethod` machanism was buggy, this is now fixed
> fix: mapPrivatePropertiesAndMethod should not be mandatory

- CHANGELOG.md
- composer.json
- src/AutoMapper.php
- tests/Extractor/FromSourceMappingExtractorTest.php
- tests/Extractor/FromTargetMappingExtractorTest.php
- tests/MapperGeneratorMetadataFactoryTest.php
Because it's the default extractor in Symfony nowadays.
> Use PhpStanExtractor instead of PhpDocExtractor

- CHANGELOG.md
- src/Extractor/ClassMethodToCallbackExtractor.php
- tests/Extractor/ClassMethodToCallbackExtractorTest.php
- tests/Fixtures/Transformer/CustomTransformer/FromTargetCustomModelTransformer.php
- tests/Fixtures/Transformer/CustomTransformer/SourceTargetCustomModelTransformer.php
> fix: allow usage of imported class names in custom transformers

- CHANGELOG.md
- src/Generator/MapMethodStatementsGenerator.php
- src/Generator/MapperGenerator.php
- tests/AutoMapperTest.php
This PR adds some phpdoc in generated mappers, which could be useful when debugging:
example:
```php
/** @param array $value */   <== phpdoc added here
public function &map($value, array $context = array()) : mixed
{
if (null === $value) {
return $value;
}
/** @var \AutoMapper\Tests\Fixtures\AddressDTOSecondReadonlyClass $result */    <== and here
$result = $context['target_to_populate'] ?? null;
// ...
}
```
> minor: add phpDoc in mappers

- src/Extractor/ReadAccessor.php
- src/GeneratedMapper.php
- src/Generator/MapperConstructorGenerator.php
- src/Generator/PropertyConditionsGenerator.php
- src/Generator/PropertyStatementsGenerator.php
- src/MapperContext.php
- tests/AutoMapperTest.php
- tests/Fixtures/Uninitialized.php
- tests/MapperContextTest.php
- tools/phpstan/phpstan-baseline.neon
Fixes #43 
Instead of getting the value we do a check on whether the value is null or undefined, this allow skipping mapping uninitialized property also.
Without this change it php would throw an error as we try to get a uninitialized property value
> feat(generator): allow skipping uninitialized property when skipping null values

- src/AutoMapper.php
- tests/AutoMapperBaseTest.php
- tests/AutoMapperTest.php
- tests/Transformer/ChainTransformerFactoryTest.php
- tests/Transformer/EvalTransformerTrait.php
- tests/Transformer/MultipleTransformerFactoryTest.php
- tests/Transformer/NullableTransformerFactoryTest.php
- tests/Transformer/UniqueTypeTransformerFactoryTest.php
There is still the `forMember` deprecation, but we should remove it in 9.0 since there is no direct replacement for it
> chore(test): remove most of deprecations in test

- composer.json
This allow to make it work with all symfony maintained versions (which should be our goal IMO)
> chore(deps): allow to use sf 5.4 for most things, remove useless deps / suggests

- CHANGELOG.md
- src/Transformer/MultipleTransformer.php
- tests/AutoMapperTest.php
- tests/Fixtures/ObjectsUnion/Bar.php
- tests/Fixtures/ObjectsUnion/Foo.php
- tests/Fixtures/ObjectsUnion/ObjectsUnionProperty.php
before this PR, an error would have occurred when trying to map a property which is an union of several objects.
This code:
```php
private Foo|Bar $prop
```
was generating this mapper:
```php
if (\AutoMapper\MapperContext::isAllowedAttribute($context, 'prop', isset($value->prop))) {
$value_1 = $value->prop;
if (is_object($value->prop)) {
// map form Foo
}
if (is_object($value->prop)) {
// map form Bar
}
$result['prop'] = $value_1;
}
```
so it never tried to handle case when `$prop` is `Bar`
now, it adds an `instanceof`:
```php
if (\AutoMapper\MapperContext::isAllowedAttribute($context, 'prop', isset($value->prop))) {
$value_1 = $value->prop;
if (is_object($value->prop) && $value->prop instanceof Foo) {
// map form Foo
}
if (is_object($value->prop) && $value6->prop instanceof Bar) {
// map …
```
> fix: allow unions with several object classes

- docs/index.md
- src/Attribute/MapFrom.php
- src/Attribute/MapTo.php
- src/Event/GenerateMapperEvent.php
- src/EventListener/MapToListener.php
- src/EventListener/MapToMapperListener.php
- src/Exception/BadMapDefinitionException.php
- src/Metadata/MapperMetadata.php
- src/Metadata/MetadataRegistry.php
- src/Transformer/CallableTransformer.php
- src/Transformer/CustomTransformer/CustomTransformersRegistry.php
- tests/AutoMapperMapToTest.php
- tests/Fixtures/MapTo/BadMapTo.php
- tests/Fixtures/MapTo/BadMapToTransformer.php
- tests/Fixtures/MapTo/Bar.php
- tests/Fixtures/MapTo/FooMapTo.php
Add `#[MapTo]` attribute which allows to : 
* Add a mapping on a previously not found property
* Ignore a property during a Map ref #16 
* Customize the target property ref #34 
* Allow to use a custom transformer : callable / transformer service ref #28
> feat(attribute): add map to attribute

- src/Transformer/ObjectTransformerFactory.php
This may happens than extractor give "special" classes (thing like a template) for the moment we don't support this, but at least don't throw error in this case
> fix(transformer): check class exists when checking reflection class in object transformer factory

- src/Extractor/FromSourceMappingExtractor.php
- src/Extractor/FromTargetMappingExtractor.php
- src/Extractor/GetTypeTrait.php
- src/Extractor/MappingExtractorInterface.php
- src/Extractor/ReadAccessor.php
- src/Extractor/ReadWriteTypeExtractor.php
- src/Extractor/SourceTargetMappingExtractor.php
- src/Extractor/WriteMutator.php
- src/Metadata/MetadataRegistry.php
- src/Symfony/Bundle/DependencyInjection/Compiler/PropertyInfoPass.php
- tests/AutoMapperTest.php
- tests/Fixtures/DifferentSetterGetterType.php
- tests/Fixtures/UserPromoted.php
Partially fix https://github.com/jolicode/automapper/issues/5
> fix(types): try to get types from read accessor / write mutator first

- composer.json
- src/Attribute/MapFrom.php
- src/Attribute/MapTo.php
- src/Event/PropertyMetadataEvent.php
- src/EventListener/MapFromListener.php
- src/EventListener/MapToListener.php
- src/Generator/MapMethodStatementsGenerator.php
- src/Generator/MapperGenerator.php
- src/Generator/PropertyConditionsGenerator.php
- src/Generator/PropertyStatementsGenerator.php
- src/Metadata/MetadataRegistry.php
- src/Metadata/PropertyMetadata.php
- tests/AutoMapperMapToTest.php
- tests/Fixtures/MapTo/FooMapTo.php
There were certainly be edge case, but i think a lot of use cases can already be handled with that
Just wondering if having expression language as a deps is wanted or do we want to make this feature optional ?
Miss documentation, will add it tomorrow
> feat(if): add if feature to map to / map from attributes

- src/Attribute/MapFrom.php
- src/Attribute/MapTo.php
- src/EventListener/MapFromListener.php
- src/EventListener/MapToListener.php
- src/Generator/CreateTargetStatementsGenerator.php
- src/Generator/PropertyStatementsGenerator.php
- src/Generator/Shared/DiscriminatorStatementsGenerator.php
- src/Metadata/MetadataRegistry.php
- src/Metadata/PropertyMetadata.php
- src/Transformer/AllowNullValueTransformerInterface.php
- src/Transformer/CallableTransformer.php
- src/Transformer/PropertyTransformer/PropertyTransformer.php
- tests/AutoMapperMapToTest.php
- tests/Fixtures/MapTo/FooMapTo.php
This allow to declare a MapTo / MapFrom in the class, useful when there is no relation to a field, in the case transformer will use the source object
> feat(map-to): allow map to / from attribute in class when declaring a transformer and a name

- src/AutoMapper.php
- src/EventListener/MapListener.php
- src/EventListener/Symfony/AdvancedNameConverterListener.php
- src/GeneratedMapper.php
- src/Generator/MapMethodStatementsGenerator.php
- src/Generator/MapperGenerator.php
- src/Generator/PropertyConditionsGenerator.php
- src/Generator/PropertyStatementsGenerator.php
- src/Metadata/MetadataRegistry.php
- src/Symfony/Attribute/AsAutoMapperExpressionService.php
- src/Symfony/Bundle/DependencyInjection/AutoMapperExtension.php
- src/Symfony/Bundle/config/automapper.php
- src/Symfony/Bundle/config/event.php
- src/Symfony/Bundle/config/expression_language.php
- src/Symfony/Bundle/config/generator.php
- src/Symfony/Bundle/config/symfony.php
- src/Symfony/ExpressionLanguageProvider.php
- src/Transformer/ExpressionLanguageTransformer.php
- tests/AutoMapperBaseTest.php
- tests/AutoMapperMapToTest.php
- tests/Bundle/Fixtures/FooMapTo.php
- tests/Bundle/Resources/App/AppKernel.php
- tests/Bundle/Resources/App/Service/FooService.php
- tests/Bundle/Resources/App/Service/IdNameConverter.php
- tests/Bundle/Resources/App/Service/YearOfBirthTransformer.php
- tests/Bundle/Resources/App/config.yml
- tests/Bundle/ServiceInstantiationTest.php
- tests/Fixtures/MapTo/FooMapTo.php
This allow to use expression language with transformer of MapTo / MapFrom attribute
Also this PR add a function provider which will allow us to directly use service inside expression language without having to create a class
Still in draft : i want to bind this to the bundle to make it work nicely
> feat(transformer): allow expression language for transformer, add provider for custom functions

- .github/workflows/documentation.yml
- CHANGELOG.md
- mkdocs.yaml
- poetry.lock
- pyproject.toml
A simple version for now, I will do a better script later on with a matrix, rn it's all static in the CI script
> Add doc versioning

- docs/bundle/configuration.md
- src/Loader/FileLoader.php
- src/Loader/FileReloadStrategy.php
- src/Symfony/Bundle/DependencyInjection/AutoMapperExtension.php
- src/Symfony/Bundle/DependencyInjection/Configuration.php
- src/Symfony/Bundle/config/automapper.php
- src/Symfony/Bundle/config/metadata.php
- tests/Bundle/Resources/config/packages/automapper.yaml
This replace the `hot_reload` with a strategy that also allows to always generate the mappers even if no change.
This is useful for us when we change something that could not be detected, this will also defnitely be useful for users in debug env when we will collect metadata for generator, this will avoid collecting only on the first "request" and avoid confusion.
Never strategy is the default one in non debug for further optimization.
> feat(loader): add reload strategy, rewamp hot_reload

- src/AutoMapper.php
- src/Generator/InjectMapperMethodStatementsGenerator.php
- src/Generator/MapperGenerator.php
- src/Generator/Shared/ClassDiscriminatorResolver.php
- src/Generator/Shared/DiscriminatorStatementsGenerator.php
- src/Metadata/MetadataFactory.php
- src/Symfony/Bundle/Resources/config/metadata.php
- src/Transformer/MapperDependency.php
- src/Transformer/ObjectTransformer.php
- tests/Bundle/Resources/App/Api/Processor/BookProcessor.php
- tests/Bundle/Resources/config/packages/automapper.yaml
- tests/Bundle/ServiceInstantiationTest.php
- tests/Metadata/MetadataFactoryTest.php
This fix a bug where when registering a class that have discriminator mapping it's sub classes would not be registered and created during warmup
> fix(metadata): fix generating discriminator dependencies

- src/Transformer/PropertyTransformer/PropertyTransformer.php
- tests/AutoMapperTest.php
- tests/Fixtures/Issue111/Colour.php
- tests/Fixtures/Issue111/ColourTransformer.php
- tests/Fixtures/Issue111/Foo.php
- tests/Fixtures/Issue111/FooDto.php
Fix https://github.com/jolicode/automapper/issues/111
> fix(transformer): fix property transformer with adder and remover methods

- docs/mapping/attributes.md
- src/Attribute/MapFrom.php
- src/Attribute/MapTo.php
- src/Event/PropertyMetadataEvent.php
- src/EventListener/MapFromListener.php
- src/EventListener/MapToListener.php
- tests/AutoMapperMapToTest.php
- tests/Fixtures/MapTo/PriorityMapTo.php
This make those attributes consistent with the way of the `#[Mapper]` attribute works
I think the priority system is better than throwing an exception, and would use case that were not possible before
> feat(attribute): allow multiple source/target, allow overriding attribute with priority system

- src/AutoMapper.php
- src/Exception/AutoMapperException.php
- src/Exception/BadMapDefinitionException.php
- src/Exception/CompileException.php
- src/Exception/InvalidArgumentException.php
- src/Exception/InvalidMappingException.php
- src/Exception/LogicException.php
- src/Exception/MetadataException.php
- src/Exception/MissingConstructorArgumentsException.php
- src/Exception/RuntimeException.php
- src/Extractor/ReadAccessor.php
- src/Generator/CreateTargetStatementsGenerator.php
- src/Generator/MapperGenerator.php
- src/Generator/PropertyConditionsGenerator.php
- src/Loader/FileLoader.php
- src/MapperContext.php
- src/Transformer/ExpressionLanguageTransformer.php
- src/Transformer/FixedValueTransformer.php
- tests/AutoMapperTest.php
- tests/MapperContextTest.php
This implement the following pattern : 
* All exceptions throw by the lib implement the `AutoMapperException` interface
* Split exceptions in 3 categories : 
* MetadataException : happens when loading metadata
* CompileException : happens when generating code
* RuntimeException : happens when executing the mapping
> feat(exceptions): better exception naming, add interface to group all exceptions

- CHANGELOG.md
- src/Symfony/Bundle/DataCollector/MetadataCollector.php
- src/Symfony/Bundle/Resources/views/DataCollector/metadata.html.twig
- tests/Bundle/ServiceInstantiationTest.php
Fixes #123 
We changed some stuff about Metadata which was not impacted within the Symfony WebProfiler
> Fix WebProfiler issues

- CHANGELOG.md
- composer.json
Because they are required to make AutoMapper works, no reason not to put them.
Will fix a part of https://github.com/jolicode/automapper/issues/127, but not everything.
> Require mandatory packages

- CHANGELOG.md
- src/Symfony/Bundle/Resources/config/event_serializer.php
- src/Symfony/Bundle/Resources/config/generator.php
`symfony/serializer` should not be required when installing AutoMapper, so with this PR I make the `ClassDiscriminatorResolver` optional within the bundle so we can install it without the Serializer installed.
Will fix a part of #127, but not everything.
> Make ClassDiscriminatorResolver optional

- src/Metadata/MapperMetadata.php
If `$this->source` is a class, it cannot be `array`. This is the same condition for `$this->target` just below.
Introduced by https://github.com/jolicode/automapper/commit/d8c708d3a199a9f5e02c2a5075a539219a9fc978#diff-4c1e0a70928058f8c9f0eb96b64ef30126ebaef5dfc1567f78dea8804c4b0f2cR28
> Remove useless condition in `MapperMetadata`

- CHANGELOG.md
- src/Metadata/MapperMetadata.php
> Make MapperMetadata non-internal because it is used within PropertyTransformerSupportInterface interface

- docs/bundle/configuration.md
Fixing little mistake in Symfony bundle configuration documentation.
Bundle await for `mapping` but documentation show `mappings`
> fix(doc): typing error in Configuration for Symfony

- composer.json
- src/Generator/CreateTargetStatementsGenerator.php
- src/Generator/PropertyConditionsGenerator.php
- src/Transformer/ArrayTransformer.php
- src/Transformer/BuiltinTransformer.php
- src/php-parser.php
- tools/phpstan/composer.lock
I think since the `Automapper` is the only entrypoint of this whole lib, we can add `class_alias()` in this class, and problem would be solved.
WDYT?
> fix: handle deprecated class LNumber in nikic/php-parser v5

- docs/bundle/cache-warmup.md
regarding [the declared configuration](https://github.com/jolicode/automapper/blob/main/src/Symfony/Bundle/DependencyInjection/Configuration.php#L56) the right key is `mapping` and not `mappings`
> docs: fix typo

- CHANGELOG.md
- composer.json
- src/Symfony/Bundle/DependencyInjection/AutoMapperExtension.php
- tests/Bundle/DependencyInjection/AutoMapperExtensionTest.php
Currently, because of parameter precedence, `$reloadStrategy` is never read from bundle config and always default to `ALWAYS` :see_no_evil:
> fix(bundle): actually read reload_strategy from bundle configuration

- CHANGELOG.md
- docs/mapping/transformer.md
Metadata property is named `property`, not `name` anymore :wink:
> docs: Fix property metadata attribute name

- docs/mapping/provider.md
Fixed a typo in the docs that was made unable to use custom providers.
> docs: Fix provider service tag

- .github/workflows/ci.yml
- src/Generator/CreateTargetStatementsGenerator.php
- src/Transformer/AbstractArrayTransformer.php
- tests/Fixtures/ConstructorWithDefaultValues.php
When using an argument with a default array value in a constructor, AutoMapper had issues using the default value if you pass no values in the `->map()` input.
Before:
```php
if (\AutoMapper\MapperContext::hasConstructorArgument($context, 'AppBundle\\Entity\\Crawl\\Metadata\\Stats\\Stats', 'fourreTout')) {
$values_2 = array();
foreach ($value['fourreTout'] as $key_2 => $value_3) {
$values_2[$key_2] = $value_3;
}
$constructarg_8 = $values_2 ?? \AutoMapper\MapperContext::getConstructorArgument($context, 'AppBundle\\Entity\\Crawl\\Metadata\\Stats\\Stats', 'fourreTout');
} else {
$values_2 = array();
foreach ($value['fourreTout'] as $key_2 => $value_3) {
$values_2[$key_2] = $value_3;
}
$constructarg_8 = $values_2 ?? array();
}
```
After:
```php
if …
```
> Constructor with default paramater array does not work

- docs/getting-started/configuration.md
Hello,
I noticed that you changed the default constructor strategy from "always" to "auto", so I updated the documentation
I hope that's OK for you
Have a great day
> fix(doc): Updating getting-started default constructor strategy

- CHANGELOG.md
- composer.json
- src/AutoMapper.php
- src/Loader/FileLoader.php
- src/Symfony/Bundle/DependencyInjection/AutoMapperExtension.php
- src/Symfony/Bundle/Resources/config/automapper.php
- tests/Bundle/DependencyInjection/AutoMapperExtensionTest.php
There can be race condition when multiple php process would generate the class at the same time, so we add a lock here to avoid this problem
[Better diff with `?w=1`](https://github.com/jolicode/automapper/pull/174/files?w=1)
> feat(loader): lock load class on file loader to avoid race condition

- CHANGELOG.md
- src/Attribute/Mapper.php
- src/Configuration.php
- src/Event/GenerateMapperEvent.php
- src/EventListener/MapperListener.php
- src/Generator/MapperGenerator.php
- src/Loader/EvalLoader.php
- src/Loader/FileLoader.php
- src/Metadata/GeneratorMetadata.php
- src/Metadata/MetadataFactory.php
- src/php-parser.php
- tests/AutoMapperTest.php
- tests/Fixtures/IntDTO.php
- tests/Fixtures/IntDTOWithMapper.php
PHP, by default, will coerce values of the wrong type into the expected scalar type declaration if possible. This leads to unexpected behavior. For example, losing decimal digits when casting float to int
```PHP
readonly class IntDto
{
public function __construct(
public int $var,
) {}
}
$autoMapper = \AutoMapper\AutoMapper::create();
$result = $autoMapper->map(['var' => 1.1111], IntDto::class);
$result->var; // var is 1
```
This PR adds configuration to add `declare(strict_types=1)` to generated code when mapping, so instead of unexpected behavior, you get TypeError.
If everything is ok, I will update the docs, but I am not very fluent with english, so maybe someone else could write a more understandable description.
> feat: option to generate code with strict types

- CHANGELOG.md
- src/Transformer/NullableTransformerFactory.php
- tests/AutoMapperTest.php
I was trying to understand why generated code looks weird when mapping from array/stdClass to class which has constructor with nullable/optional arguments.
NullableTransformer is not supposed to be applied when creating from constructor because nullable/optional already handled.
With this fix, generated code instead of looking like this:
```PHP
$value_1 = null;
if (null !== $value->ResponseDescription) {
$value_1 = $value->ResponseDescription;
}
$constructarg_1 = $value_1 ?? NULL;
``` 
Look like this:
```PHP
$constructarg_1 = $value->ResponseDescription ?? NULL;
```
Which also fixes #181
> fix: error when mapping from stdClass to constructor with nullable/optional arguments

- CHANGELOG.md
- src/Generator/CreateTargetStatementsGenerator.php
- tests/AutoMapperTest.php
After this PR #177 behavior was fixed when not using constructor arguments context, but with context it's still uses `??`.
Before:
```PHP
if (\AutoMapper\MapperContext::hasConstructorArgument($context, 'ConstructorWithDefaultValues', 'someOtters')) {
$values = [];
foreach ($value['someOtters'] ?? [] as $key => $value) {
$values[$key] = $value;
}
$constructarg = $values ?? \AutoMapper\MapperContext::getConstructorArgument($context, 'ConstructorWithDefaultValues', 'someOtters');
} else {
$values = [];
foreach ($value['someOtters'] ?? [] as $key => $value) {
$values[$key] = $value;
}
$constructarg = count($values) > 0 ? $values : array();
}
```
After:
```PHP
if (\AutoMapper\MapperContext::hasConstructorArgument($context, 'ConstructorWithDefaultValues', 'someOtters')) {
$values = [];
foreach …
```
> fix: constructor with default parameter array does not work with context

- CHANGELOG.md
- src/Transformer/NullableTransformer.php
- src/Transformer/NullableTransformerFactory.php
- tests/Fixtures/ConstructorWithDefaultValues.php
Turns out NullableTransformer is needed when creating from constructor if we have argument what expects nullable object
> fix: regression after #184

- CHANGELOG.md
- src/Symfony/Bundle/Resources/views/DataCollector/icon.svg
- src/Symfony/Bundle/Resources/views/DataCollector/metadata.html.twig
- hide automapper from profiler if there's no map action
- add icon to symfony profiler
I'm using this icon https://tabler.io/icons/icon/topology-full let me know if the icon needs to be changed
> add icon to symfony profiler

- CHANGELOG.md
- src/Transformer/CallableTransformer.php
- tests/Fixtures/MapTo/Bar.php
> fix: source and context not passed to callable transformer

- CHANGELOG.md
- src/Generator/CreateTargetStatementsGenerator.php
When object gets created from constructor, there are always checks for constructor arguments in context. This eats some of performance, especially if you don't use context. When looking at the generated code, I noticed that it can be optimized a little.
I didn't benchmark it a lot, but I did see around 10% more performance with this optimization
Before:
```php
if (\AutoMapper\MapperContext::hasConstructorArgument($context, 'Dto', 'propertyName')) {
$constructarg = $source->propertyName ?? \AutoMapper\MapperContext::getConstructorArgument($context, 'Dto', 'propertyName');
} else {
$constructarg = $source->propertyName ?? throw new \AutoMapper\Exception\MissingConstructorArgumentsException('Cannot create an instance ...');
}
```
After:
```php
$constructarg = $source->propertyName ?? ( …
```
> Optimize creation from constructor

- src/Attribute/MapFrom.php
- src/Attribute/MapTo.php
According to the `PropertyTransformerInterface`, the signature of a transformer should be: 
```php
/**
* @param mixed                       $value   the value of the property to transform, can be null if there is no way to read the data from the mapping
* @param object|array<string, mixed> $source  the source input on which the custom transformation applies
* @param array<string, mixed>        $context Context during mapping
*/
public function transform(mixed $value, object|array $source, array $context): mixed;
```
> fix: signature of Map attributes `transformer` property

- CHANGELOG.md
- composer.json
- src/Extractor/GetTypeTrait.php
I noticed locally that random test started to fail, turns out it's because [phpdocumentor/type-resolver added support for phpstan/phpdoc-parser v2](https://github.com/phpDocumentor/TypeResolver/releases/tag/1.10.0), but this library not ready for phpdoc-parser v2.
I chose minimal version of 1.13 because minimal version of [phpdocumentor/type-resolver required it](https://github.com/phpDocumentor/TypeResolver/blob/1.7.0/composer.json#L15) so there should be no changes to `composer update --prefer-lowest`
> Add support for phpstan/phpdoc-parser 2

- CHANGELOG.md
- src/Extractor/FromSourceMappingExtractor.php
- src/Metadata/MetadataFactory.php
- src/php-parser.php
Deprecated since PHP 8.4, see https://wiki.php.net/rfc/deprecate-implicitly-nullable-types
> fix: implicity nullable parameter deprecations

- CHANGELOG.md
- src/Transformer/AbstractArrayTransformer.php
- tests/AutoMapperTest.php
- tests/Fixtures/PetOwnerWithConstructorArguments.php
After some attempts, I came to this solution for this issue: https://github.com/jolicode/automapper/issues/211.
Not sure if it's the right thing to do.
> fix: handle case where class target has adder and remover AND constructor arguments

- src/Generator/CreateTargetStatementsGenerator.php
- tests/AutoMapperTest.php
- tests/Fixtures/ConstructorWithDefaultValuesAsObjects.php
While working on #187 I noticed what you can't map to a class that has constructor with default values as objects if source missing these arguments.
Seems like a complex issue to fix, so I'll start with the tests
> fix: constructor with default values as objects

- docs/bundle/configuration.md
Fix: 
https://symfony.com/blog/new-in-symfony-3-2-php-constants-in-yaml-files
> Update invalid syntax in configuration.md for constant

- docs/getting-started/configuration.md
- src/Attribute/Mapper.php
- src/Configuration.php
- src/Event/GenerateMapperEvent.php
- src/EventListener/MapperListener.php
- src/Extractor/FromSourceMappingExtractor.php
- src/Extractor/FromTargetMappingExtractor.php
- src/Extractor/MappingExtractor.php
- src/Extractor/ReadAccessor.php
- src/Metadata/MetadataFactory.php
- tests/AutoMapperTest/ArrayAccess/expected.1.data
- tests/AutoMapperTest/ArrayAccess/expected.data
- tests/AutoMapperTest/ArrayAccess/map.php
Replace https://github.com/jolicode/automapper/pull/144
Basically this allow to map to or from an object implementing the ArrayAccess interface
> feat(array-access): allow to map extra properties

- src/AutoMapper.php
- src/Event/PropertyMetadataEvent.php
- src/Metadata/MetadataFactory.php
- tests/AutoMapperBuilder.php
- tests/Fixtures/User.php
- tests/Normalizer/AutoMapperNormalizerTest.php
Fix https://github.com/jolicode/automapper/issues/238
This does not change the current behavior as it's a BC break for existing app, however it add a flag and deprecation notice that warn user that this behavior will change in the next major release.
I also use ignore : true so we can show why it's not mapped for the user
> feat(extractor): remove default property mapping, if at least one attribute is set

- castor.php
- src/Attribute/MapFrom.php
- src/Attribute/MapTo.php
- src/Configuration.php
- src/Event/PropertyMetadataEvent.php
- src/EventListener/MapFromListener.php
- src/EventListener/MapToListener.php
- src/Extractor/FromSourceMappingExtractor.php
- src/Extractor/FromTargetMappingExtractor.php
- src/Extractor/MappingExtractorInterface.php
- src/Extractor/ReadWriteTypeExtractor.php
- src/Extractor/SourceTargetMappingExtractor.php
- src/Metadata/MetadataFactory.php
- tests/AutoMapperTest/Covariance/expected.data
- tests/AutoMapperTest/Covariance/map.php
Fix https://github.com/jolicode/automapper/issues/190
> feat(types): allow to extract from getter on target

- src/Extractor/MappingExtractor.php
- src/Extractor/ReadAccessor.php
- src/Extractor/WriteMutator.php
- src/Transformer/AbstractArrayTransformer.php
- src/Transformer/DoctrineCollectionTransformerFactory.php
- tests/AutoMapperTest.php
- tests/AutoMapperTest/ArrayConsistency/expected.to.data
- tests/AutoMapperTest/ArrayConsistency/expected.toAdder.data
- tests/AutoMapperTest/ArrayConsistency/expected.toAdderCollection.data
- tests/AutoMapperTest/ArrayConsistency/expected.toCollection.data
- tests/AutoMapperTest/ArrayConsistency/map.php
- tests/Fixtures/PetOwner.php
Fix https://github.com/jolicode/automapper/issues/227
> feat(remover): remove existing values when adder and remover

- src/AutoMapper.php
- src/Transformer/AbstractArrayTransformer.php
- src/Transformer/ArrayToDoctrineCollectionTransformer.php
- src/Transformer/ObjectTransformer.php
- tests/AutoMapperTest/ArrayConsistency/map.php
I think having this to true by default if we pass an existing value is better for DX, i kind of expect that by default when passing a value (having to set this value should be only opt out)
> feat(mapper): set deep populate to true if passing an existing value

- CHANGELOG.md
- src/Extractor/GetTypeTrait.php
To test it, I forced 7.3@beta in the `composer.json`. But I didn't commit it!
```
>…re/dev/github.com/jolicode/automapper(sf7-3 *) composer show symfony/property-info
name     : symfony/property-info
descrip. : Extracts information about PHP class' properties using metadata of popular sources
keywords : doctrine, phpdoc, property, symfony, type, validator
versions : * v7.3.0-BETA1
released : 2025-04-04, 3 weeks ago
type     : library
license  : MIT License (MIT) (OSI approved) https://spdx.org/licenses/MIT.html#licenseText
homepage : https://symfony.com
source   : [git] https://github.com/symfony/property-info.git 200d230d8553610ada73ac557501dc4609aad31f
dist     : [zip] https://api.github.com/repos/symfony/property-info/zipball/200d230d8553610ada73ac557501dc4609aad31f …
```
> Fix support for symfony/property-info 7.3@beta

- CHANGELOG.md
- src/Generator/MapMethodStatementsGenerator.php
- tests/AutoMapperTest.php
- tests/Fixtures/Category.php
- tests/Fixtures/CategoryDTO.php
- tests/Fixtures/Post.php
- tests/Fixtures/PostDTO.php
Updates the generated mapper code such that circular references are handled properly when using promoted properties.
Solves #271
> fix(constructor): fixed circular references with promoted properties

- CHANGELOG.md
- src/Generator/PropertyConditionsGenerator.php
This PR reorders the generated condition checks in the generate() method to prioritize the customCondition() check before other standard conditions.
In the generated mapper code, this change allows custom condition to occur earlier. As a result, potentially heavy methods, such as those that may trigger database queries are not executed if the custom condition fails.
Before:
```php
if (isAllowedAttribute(...) && groupsCheck(...) && customCondition(...)) { // DB hit
$result->someProperty = $value->someMethod(); // DB hit
}
```
After:
```php
if (customCondition(...) && isAllowedAttribute(...) && groupsCheck(...)) {
$result->someProperty = $value->someMethod(); // DB hit only if needed
}
```
> Optimize condition order to avoid unnecessary method calls in AutoMapper
